const OPCODE_MAP = {
  0x00: { instruction: "NOP", len: 1 },
  0x01: { instruction: "LXI B,D16", len: 3 },
  0x02: { instruction: "STAX B", len: 1 },
  0x03: { instruction: "INX B", len: 1 },
  0x04: { instruction: "INR B", len: 1 },
  0x05: { instruction: "DCR B", len: 1 },
  0x06: { instruction: "MVI B, D8", len: 2 },
  0x07: { instruction: "RLC", len: 1 },
  0x09: { instruction: "DAD B", len: 1 },
  0x0a: { instruction: "LDAX B", len: 1 },
  0x0b: { instruction: "DCX B", len: 1 },
  0x0c: { instruction: "INR C", len: 1 },
  0x0d: { instruction: "DCR C", len: 1 },
  0x0e: { instruction: "MVI C, D8", len: 2 },
  0x0f: { instruction: "RRC", len: 1 },
  0x11: { instruction: "LXI D,D16", len: 3 },
  0x12: { instruction: "STAX D", len: 1 },
  0x13: { instruction: "INX D", len: 1 },
  0x14: { instruction: "INR D", len: 1 },
  0x15: { instruction: "DCR D", len: 1 },
  0x16: { instruction: "MVI D, ", len: 2 },
  0x17: { instruction: "RAL", len: 1 },
  0x19: { instruction: "DAD D", len: 1 },
  0x1a: { instruction: "LDAX D", len: 1 },
  0x1b: { instruction: "DCX D", len: 1 },
  0x1c: { instruction: "INR E", len: 1 },
  0x1d: { instruction: "DCR E", len: 1 },
  0x1e: { instruction: "MVI E,", len: 2 },
  0x1f: { instruction: "RAR", len: 1 },
  0x20: { instruction: "RIM", len: 1 },
  0x21: { instruction: "LXI H,D16", len: 3 },
  0x22: { instruction: "SHLD ", len: 3 },
  0x23: { instruction: "INX H", len: 1 },
  0x24: { instruction: "INR H", len: 1 },
  0x25: { instruction: "DCR H", len: 1 },
  0x26: { instruction: "MVI H, D8", len: 2 },
  0x27: { instruction: "DAA", len: 1 },
  0x29: { instruction: "DAD H", len: 1 },
  0x2a: { instruction: "LHLD ", len: 3 },
  0x2b: { instruction: "DCX H", len: 1 },
  0x2c: { instruction: "INR L", len: 1 },
  0x2d: { instruction: "DCR L", len: 1 },
  0x2e: { instruction: "MVI L, ", len: 2 },
  0x2f: { instruction: "CMA", len: 1 },
  0x30: { instruction: "SIM", len: 1 },
  0x31: { instruction: "LXI SP,D16", len: 3 },
  0x32: { instruction: "STA adr", len: 3 },
  0x33: { instruction: "INX SP", len: 1 },
  0x34: { instruction: "INR M", len: 1 },
  0x35: { instruction: "DCR M", len: 1 },
  0x36: { instruction: "MVI M, D8", len: 2 },
  0x37: { instruction: "STC", len: 1 },
  0x39: { instruction: "DAD SP", len: 1 },
  0x3a: { instruction: "LDA adr", len: 3 },
  0x3b: { instruction: "DCX SP", len: 1 },
  0x3c: { instruction: "INR A", len: 1 },
  0x3d: { instruction: "DCR A", len: 1 },
  0x3e: { instruction: "MVI A, D8", len: 2 },
  0x3f: { instruction: "CMC", len: 1 },
  0x40: { instruction: "MOV B,B", len: 1 },
  0x41: { instruction: "MOV B,C", len: 1 },
  0x42: { instruction: "MOV B,D", len: 1 },
  0x43: { instruction: "MOV B,E", len: 1 },
  0x44: { instruction: "MOV B,H", len: 1 },
  0x45: { instruction: "MOV B,L", len: 1 },
  0x46: { instruction: "MOV B,M", len: 1 },
  0x47: { instruction: "MOV B,A", len: 1 },
  0x48: { instruction: "MOV C,B", len: 1 },
  0x49: { instruction: "MOV C,C", len: 1 },
  0x4a: { instruction: "MOV C,D", len: 1 },
  0x4b: { instruction: "MOV C,E", len: 1 },
  0x4c: { instruction: "MOV C,H", len: 1 },
  0x4d: { instruction: "MOV C,L", len: 1 },
  0x4e: { instruction: "MOV C,M", len: 1 },
  0x4f: { instruction: "MOV C,A", len: 1 },
  0x50: { instruction: "MOV D,B", len: 1 },
  0x51: { instruction: "MOV D,C", len: 1 },
  0x52: { instruction: "MOV D,D", len: 1 },
  0x53: { instruction: "MOV D,E", len: 1 },
  0x54: { instruction: "MOV D,H", len: 1 },
  0x55: { instruction: "MOV D,L", len: 1 },
  0x56: { instruction: "MOV D,M", len: 1 },
  0x57: { instruction: "MOV D,A", len: 1 },
  0x58: { instruction: "MOV E,B", len: 1 },
  0x59: { instruction: "MOV E,C", len: 1 },
  0x5a: { instruction: "MOV E,D", len: 1 },
  0x5b: { instruction: "MOV E,E", len: 1 },
  0x5c: { instruction: "MOV E,H", len: 1 },
  0x5d: { instruction: "MOV E,L", len: 1 },
  0x5e: { instruction: "MOV E,M", len: 1 },
  0x5f: { instruction: "MOV E,A", len: 1 },
  0x60: { instruction: "MOV H,B", len: 1 },
  0x61: { instruction: "MOV H,C", len: 1 },
  0x62: { instruction: "MOV H,D", len: 1 },
  0x63: { instruction: "MOV H,E", len: 1 },
  0x64: { instruction: "MOV H,H", len: 1 },
  0x65: { instruction: "MOV H,L", len: 1 },
  0x66: { instruction: "MOV H,M", len: 1 },
  0x67: { instruction: "MOV H,A", len: 1 },
  0x68: { instruction: "MOV L,B", len: 1 },
  0x69: { instruction: "MOV L,C", len: 1 },
  0x6a: { instruction: "MOV L,D", len: 1 },
  0x6b: { instruction: "MOV L,E", len: 1 },
  0x6c: { instruction: "MOV L,H", len: 1 },
  0x6d: { instruction: "MOV L,L", len: 1 },
  0x6e: { instruction: "MOV L,M", len: 1 },
  0x6f: { instruction: "MOV L,A", len: 1 },
  0x70: { instruction: "MOV M,B", len: 1 },
  0x71: { instruction: "MOV M,C", len: 1 },
  0x72: { instruction: "MOV M,D", len: 1 },
  0x73: { instruction: "MOV M,E", len: 1 },
  0x74: { instruction: "MOV M,H", len: 1 },
  0x75: { instruction: "MOV M,L", len: 1 },
  0x76: { instruction: "HLT", len: 1 },
  0x77: { instruction: "MOV M,A", len: 1 },
  0x78: { instruction: "MOV A,B", len: 1 },
  0x79: { instruction: "MOV A,C", len: 1 },
  0x7a: { instruction: "MOV A,D", len: 1 },
  0x7b: { instruction: "MOV A,E", len: 1 },
  0x7c: { instruction: "MOV A,H", len: 1 },
  0x7d: { instruction: "MOV A,L", len: 1 },
  0x7e: { instruction: "MOV A,M", len: 1 },
  0x7f: { instruction: "MOV A,A", len: 1 },
  0x80: { instruction: "ADD B", len: 1 },
  0x81: { instruction: "ADD C", len: 1 },
  0x82: { instruction: "ADD D", len: 1 },
  0x83: { instruction: "ADD E", len: 1 },
  0x84: { instruction: "ADD H", len: 1 },
  0x85: { instruction: "ADD L", len: 1 },
  0x86: { instruction: "ADD M", len: 1 },
  0x87: { instruction: "ADD A", len: 1 },
  0x88: { instruction: "ADC B", len: 1 },
  0x89: { instruction: "ADC C", len: 1 },
  0x8a: { instruction: "ADC D", len: 1 },
  0x8b: { instruction: "ADC E", len: 1 },
  0x8c: { instruction: "ADC H", len: 1 },
  0x8d: { instruction: "ADC L", len: 1 },
  0x8e: { instruction: "ADC M", len: 1 },
  0x8f: { instruction: "ADC A", len: 1 },
  0x90: { instruction: "SUB B", len: 1 },
  0x91: { instruction: "SUB C", len: 1 },
  0x92: { instruction: "SUB D", len: 1 },
  0x93: { instruction: "SUB E", len: 1 },
  0x94: { instruction: "SUB H", len: 1 },
  0x95: { instruction: "SUB L", len: 1 },
  0x96: { instruction: "SUB M", len: 1 },
  0x97: { instruction: "SUB A", len: 1 },
  0x98: { instruction: "SBB B", len: 1 },
  0x99: { instruction: "SBB C", len: 1 },
  0x9a: { instruction: "SBB D", len: 1 },
  0x9b: { instruction: "SBB E", len: 1 },
  0x9c: { instruction: "SBB H", len: 1 },
  0x9d: { instruction: "SBB L", len: 1 },
  0x9e: { instruction: "SBB M", len: 1 },
  0x9f: { instruction: "SBB A", len: 1 },
  0xa0: { instruction: "ANA B", len: 1 },
  0xa1: { instruction: "ANA C", len: 1 },
  0xa2: { instruction: "ANA D", len: 1 },
  0xa3: { instruction: "ANA E", len: 1 },
  0xa4: { instruction: "ANA H", len: 1 },
  0xa5: { instruction: "ANA L", len: 1 },
  0xa6: { instruction: "ANA M", len: 1 },
  0xa7: { instruction: "ANA A", len: 1 },
  0xa8: { instruction: "XRA B", len: 1 },
  0xa9: { instruction: "XRA C", len: 1 },
  0xaa: { instruction: "XRA D", len: 1 },
  0xab: { instruction: "XRA E", len: 1 },
  0xac: { instruction: "XRA H", len: 1 },
  0xad: { instruction: "XRA L", len: 1 },
  0xae: { instruction: "XRA M", len: 1 },
  0xaf: { instruction: "XRA A", len: 1 },
  0xb0: { instruction: "ORA B", len: 1 },
  0xb1: { instruction: "ORA C", len: 1 },
  0xb2: { instruction: "ORA D", len: 1 },
  0xb3: { instruction: "ORA E", len: 1 },
  0xb4: { instruction: "ORA H", len: 1 },
  0xb5: { instruction: "ORA L", len: 1 },
  0xb6: { instruction: "ORA M", len: 1 },
  0xb7: { instruction: "ORA A", len: 1 },
  0xb8: { instruction: "CMP B", len: 1 },
  0xb9: { instruction: "CMP C", len: 1 },
  0xba: { instruction: "CMP D", len: 1 },
  0xbb: { instruction: "CMP E", len: 1 },
  0xbc: { instruction: "CMP H", len: 1 },
  0xbd: { instruction: "CMP L", len: 1 },
  0xbe: { instruction: "CMP M", len: 1 },
  0xbf: { instruction: "CMP A", len: 1 },
  0xc0: { instruction: "RNZ", len: 1 },
  0xc1: { instruction: "POP B", len: 1 },
  0xc2: { instruction: "JNZ adr", len: 3 },
  0xc3: { instruction: "JMP adr", len: 3 },
  0xc4: { instruction: "CNZ adr", len: 3 },
  0xc5: { instruction: "PUSH B", len: 1 },
  0xc6: { instruction: "ADI D8", len: 2 },
  0xc7: { instruction: "RST 0", len: 1 },
  0xc8: { instruction: "RZ", len: 1 },
  0xc9: { instruction: "RET", len: 1 },
  0xca: { instruction: "JZ adr", len: 3 },
  0xcc: { instruction: "CZ adr", len: 3 },
  0xcd: { instruction: "CALL adr", len: 3 },
  0xce: { instruction: "ACI D8", len: 2 },
  0xcf: { instruction: "RST 1", len: 1 },
  0xd0: { instruction: "RNC", len: 1 },
  0xd1: { instruction: "POP D", len: 1 },
  0xd2: { instruction: "JNC adr", len: 3 },
  0xd3: { instruction: "OUT D8", len: 2 },
  0xd4: { instruction: "CNC adr", len: 3 },
  0xd5: { instruction: "PUSH D", len: 1 },
  0xd6: { instruction: "SUI D8", len: 2 },
  0xd7: { instruction: "RST 2", len: 1 },
  0xd8: { instruction: "RC", len: 1 },
  0xda: { instruction: "JC adr", len: 3 },
  0xdb: { instruction: "IN D8", len: 2 },
  0xdc: { instruction: "CC adr", len: 3 },
  0xde: { instruction: "SBI D8", len: 2 },
  0xdf: { instruction: "RST 3", len: 1 },
  0xe0: { instruction: "RPO", len: 1 },
  0xe1: { instruction: "POP H", len: 1 },
  0xe2: { instruction: "JPO adr", len: 3 },
  0xe3: { instruction: "XTHL", len: 1 },
  0xe4: { instruction: "CPO adr", len: 3 },
  0xe5: { instruction: "PUSH H", len: 1 },
  0xe6: { instruction: "ANI D8", len: 2 },
  0xe7: { instruction: "RST 4", len: 1 },
  0xe8: { instruction: "RPE", len: 1 },
  0xe9: { instruction: "PCHL", len: 1 },
  0xea: { instruction: "JPE adr", len: 3 },
  0xeb: { instruction: "XCHG", len: 1 },
  0xec: { instruction: "CPE adr", len: 3 },
  0xee: { instruction: "XRI D8", len: 2 },
  0xef: { instruction: "RST 5", len: 1 },
  0xf0: { instruction: "RP", len: 1 },
  0xf1: { instruction: "POP PSW", len: 1 },
  0xf2: { instruction: "JP adr", len: 3 },
  0xf3: { instruction: "DI", len: 1 },
  0xf4: { instruction: "CP adr", len: 3 },
  0xf5: { instruction: "PUSH ", len: 1 },
  0xf6: { instruction: "ORI D8", len: 2 },
  0xf7: { instruction: "RST 6", len: 1 },
  0xf8: { instruction: "RM", len: 1 },
  0xf9: { instruction: "SPHL", len: 1 },
  0xfa: { instruction: "JM adr", len: 3 },
  0xfb: { instruction: "EI", len: 1 },
  0xfc: { instruction: "CM adr", len: 3 },
  0xfe: { instruction: "CPI D8", len: 2 },
  0xff: { instruction: "RST 7", len: 1 },
};

export default OPCODE_MAP;
